version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.8-management
        container_name: test-mq
        volumes:
            - ./rabbitmq/etc/:/etc/rabbitmq/
            - ./rabbitmq/data/:/var/lib/rabbitmq/
            - ./rabbitmq/logs/:/var/log/rabbitmq/
        ports:
            - 5672:5672
            - 15672:15672
